[package]
name = "one_hundred_days_of_code"
version = "0.1.0"
authors = ["Caleb <CalebOttoGameDev@Gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
